#!/system/bin/sh
#
# swap External to Internal For Xiaomi Redmi note version 04.10.11
# Created by FrogyFurnetal
#
########################################################################
# Constant definition
LOGPATH="/cache/Int2Ext"
DATAPATH="/data/sdcard"
SDPATH="/dev/block/vold/179:97"
DATA0PATH="/data/media/0"
DATAOBBPATH="/data/media/obb"
LOGFILE="${LOGPATH}/Int2Ext.log"
WORKDIR="${LOGPATH}"
BTMGRPATH="/system/btmgr"
# Busybox setup
if [ -x "${BTMGRPATH}/bin/busybox" ]; then
  BUSYBOX="${BTMGRPATH}/bin/busybox"
elif [ -x "/system/xbin/busybox" ]; then
  BUSYBOX="/system/xbin/busybox"
elif [ -x "/system/bin/busybox" ]; then
  BUSYBOX="/system/bin/busybox"
else
  BUSYBOX=""
fi
# Command setup
DATE="${BUSYBOX} date"
CAT="${BUSYBOX} cat"
CHOWN="${BUSYBOX} chown"
CHMOD="${BUSYBOX} chmod"
DF="${BUSYBOX} df"
MKDIR="${BUSYBOX} mkdir"
MOUNT="${BUSYBOX} mount"
UMOUNT="${BUSYBOX} umount"
MV="${BUSYBOX} mv"
RM="${BUSYBOX} rm"
TOUCH="${BUSYBOX} touch"
CHGRP="${BUSYBOX} chgrp"
GREP="${BUSYBOX} grep"
# Logfile rotation
if [ ! -d "${LOGPATH}" ];then
  ${MKDIR} ${LOGPATH}
  ${CHOWN} system.cache ${LOGPATH}
  ${CHMOD} 770 ${LOGPATH}
else
  if [ -f ${LOGFILE} ];then
    ${MV} ${LOGFILE} ${LOGFILE}.old
  fi
  ${TOUCH} ${LOGFILE}
  ${CHMOD} 660 ${LOGFILE}
fi
# Function definition for logging
ECHOL(){
  _DATETIME=`${DATE} +"%Y%m%d %H%M%S"`
  echo "${_DATETIME}: $*" >> ${LOGFILE}
  return 0
}
EXECL(){
  _DATETIME=`${DATE} +"%Y%m%d %H%M%S"`
  echo "${_DATETIME}: $*" >> ${LOGFILE}
  $* 2>> ${LOGFILE}
  _RET=$?
  echo "${_DATETIME}: RET=${_RET}" >> ${LOGFILE}
  return ${_RET}
}
# Start main routine
ECHOL "### Swapping memory start"
ECHOL "### BUSYBOX=${BUSYBOX}"
ECHOL "### "
# mounting root at read and write
ECHOL "### Mounting root as rw..."
EXECL ${MOUNT} -o rw,remount /
ECHOL "### Wait for swapping memory,..."
if ( grep -c "mmcblk1p1" /proc/partitions ); then
	sleep 5
	if [ ! -d "${DATA0PATH}" ];then
		ECHOL "### no such file or directory"
		ECHOL "### create folder /data/media/ 0 and obb"
		${MKDIR} -p "${DATA0PATH}"
		${MKDIR} -p "${DATAOBBPATH}"
	else
		ECHOL "### Folder or files found"
	fi
	ECHOL "### Mounting external memory into /data/media/0"
	EXECL ${MOUNT} -t vfat -o umask=0002,uid=1023,gid=1023 ${SDPATH} /data/media/0
	EXECL ${MOUNT} -o bind /data/media/0/Android/obb /data/media/obb
	ECHOL "### Mounting external memory into /mnt/shell/emulated/0"
	EXECL ${MOUNT} -o bind /data/media/0 /mnt/shell/emulated/0
	EXECL ${MOUNT} -o bind /data/media/0/Android/obb /mnt/shell/emulated/obb
	ECHOL "### Mounting Internal memory into /storage/sdcard1"
	if [ ! -d "${DATAPATH}" ];then
		${MKDIR} -p ${DATAPATH}
		${CHOWN} media_rw.media_rw ${DATAPATH}
		${CHMOD} 0775 ${DATAPATH}
	else
		${CHOWN} media_rw.media_rw ${DATAPATH}
		${CHMOD} 0775 ${DATAPATH}
	fi
	EXECL ${MOUNT} -o bind ${DATAPATH} /storage/sdcard1
	# Finishing
	ECHOL "### "
	ECHOL "### Swapping Memory Enable"
    break;
	# list Disk utilization
	ECHOL "### List Disk Utilization"
	ECHOL "------------ start ---------------------"
	${DF} >> ${LOGFILE}
	ECHOL "------------  end  ---------------------"
else
	# Finishing
	ECHOL "### "
	ECHOL "### no sdcard external"
	ECHOL "### Swapping Memory Disable"
fi
# mounting root at read only
ECHOL "### "
ECHOL "### remounting root as ro..."
EXECL ${MOUNT} -o ro,remount /
